stages:
  - test
  - publish

test-debug:
  image: node:6.9.1
  stage: test
  script:
    - npm install
    - npm test

release:
  image: node:6.9.1
  stage: publish
  only:
    - master
  script:
    - npm install
    - curl -u$ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD https://edify.jfrog.io/edify/api/npm/auth > ~/.npmrc
    - echo registry=http://edify.jfrog.io/edify/api/npm/npm-edify >> ~/.npmrc
    - npm publish
